#!/usr/bin/python

import cgi
import cgitb
cgitb.enable()

print "Content-type: text/html\n\n"

form = cgi.FieldStorage()

if (form.has_key("counter")):
 counter = form.getvalue("counter")
else:
 counter = -1

if (form.has_key("action")):
 action = form.getvalue("action")
else:
 action = "Up"

if (action == "Up"):
 counter= int(counter)+ 1
else:
 counter = int(counter) -1


print """
<form>
      	Welcome, you have clicked the button %s times.<br>
        <input type="hidden" name="counter" value=%s>
        <input type="submit" name="action" value="Up">
        <input type="submit" name="action" value="Down">
</form>
""" % (counter, counter)
